# Generated by Django 3.2.4 on 2021-06-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='extension',
            field=models.CharField(default='.jpg', max_length=32),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
