# Generated by Django 3.2.4 on 2021-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_service', '0002_auto_20210608_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='backend_service.album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='extension',
            field=models.CharField(default='jpeg', max_length=32),
        ),
    ]
